-- Customer Analysis

-- 1. Identify the customer type with the highest purchase frequency.
       SELECT customer_type, COUNT(customer_type) AS common_customer
       FROM AMAZON_sales_DATA  GROUP BY customer_type ORDER BY common_customer DESC LIMIT 1;

-- 2. Determine the predominant gender among customers.
       SELECT gender, COUNT(*) AS all_genders 
       FROM AMAZON_sales_DATA GROUP BY gender ORDER BY all_genders DESC LIMIT 1;

-- 3. Examine the distribution of genders within each branch.
       SELECT branch, gender, COUNT(gender) AS gender_distribution
       FROM AMAZON_sales_DATA GROUP BY branch, gender ORDER BY branch;

-- 4. Identify the time of day when customers provide the most ratings.
       SELECT branch, gender, COUNT(gender) AS gender_distribution
       FROM AMAZON_sales_DATA GROUP BY branch, gender ORDER BY branch;

-- 5. Determine the time of day with the highest customer ratings for each branch.
       SELECT branch, time_of_day, AVG(rating) AS average_rating
       FROM AMAZON_sales_DATA GROUP BY branch, time_of_day ORDER BY average_rating DESC;

-- 6. Identify the day of the week with the highest average ratings.
       SELECT day_name, AVG(rating) AS average_rating
       FROM AMAZON_sales_DATA GROUP BY day_name ORDER BY average_rating DESC LIMIT 1;

-- 7. Determine the day of the week with the highest average ratings for each branch.
       SELECT  branch, day_name, AVG(rating) AS average_rating
	   FROM AMAZON_sales_DATA GROUP BY day_name, branch ORDER BY average_rating DESC;
       
-- 8. What is the total revenue generated by different customer types for each gender in the Amazon sales data?
       SELECT Gender, Customer_type, SUM(Total) AS Total_Revenue
       FROM AMAZON_sales_DATA
       GROUP BY Gender, Customer_type;
       








       
